{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "airflow-kube-s3.fullname" . }}-web
  labels: {{ include "airflow-kube-s3.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
  annotations:
    {{ range $key, $value := .Values.ingress.web.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
{{- if .Values.ingress.web.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.web.host }}
      secretName: {{ .Values.ingress.web.tls.secretName }}
{{- end }}
  rules:
    - http:
        paths:
          - path: {{ .Values.ingress.web.path }}
            backend:
              serviceName: {{ template "airflow-kube-s3.fullname" . }}-web
              servicePort: http
      host: {{ .Values.ingress.web.host }}
{{- end }}
