{{- if .Values.airflow.rbac.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "airflow-kube-s3.fullname" . }}-web
  labels: {{ include "airflow-kube-s3.labels" . | nindent 4 }}
type: Opaque
data:
  webserver_config.py: {{ .Values.airflow.web.fabConfig | b64enc | quote }}
{{- end }}
