{{- define "connections.script" }}
  #!/bin/sh -e
  {{- range .Values.airflow.connections }}
  airflow connections --add --conn_type {{ .type }} --conn_id {{ .id }}
  {{- if .uri }} --conn_uri {{ .uri | quote }} {{ end -}}
  {{- if .host }} --conn_host {{ .host | quote }} {{ end -}}
  {{- if .login }} --conn_login {{ .login | quote }} {{ end -}}
  {{- if .password }} --conn_password {{ .password | quote }} {{ end -}}
  {{- if .schema }} --conn_schema {{ .schema | quote }} {{ end -}}
  {{- if .port }} --conn_port {{ .port }} {{ end -}}
  {{- if .extra }} --conn_extra {{ .extra | quote }} {{ end -}} || true
  {{- end }}
{{- end }}

{{- define "users.script" }}
  #!/bin/sh -e
  {{- range .Values.airflow.rbac.users }}
  airflow create_user
    {{- if .firstname }} --firstname {{ .firstname | quote }}{{ end -}}
    {{- if .lastname }} --lastname {{ .lastname | quote }}{{ end -}}
    {{- if .email }} --email {{ .email | quote }}{{ end -}}
    {{- if .username }} --username {{ .username | quote }}{{ end -}}
    {{- if .role }} --role {{ .role | quote }}{{ end -}}
    {{- if .password }}
      {{- if eq .password "random" }} --use_random_password {{ else }} --password {{ .password | quote }}{{ end }}
    {{- end }} || true
  {{- end }}
{{- end }}

{{- if or .Values.airflow.connections (and .Values.airflow.rbac.enabled .Values.airflow.rbac.users) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "airflow-kube-s3.fullname" . }}-scripts
  labels: {{ include "airflow-kube-s3.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.airflow.connections }}
  add-connections.sh: {{ include "connections.script" . | b64enc }}
  {{- end }}
  {{- if .Values.airflow.rbac.users }}
  add-users.sh: {{ include "users.script" . | b64enc }}
  {{- end }}
{{- end }}
