apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "kube-web-view.fullname" . }}
  labels:
    {{- include "labels.standard" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "labels.standard" . | indent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      volumes:
        - name: secrets
          secret:
            secretName: {{ template "kube-web-view.fullname" . }}
        - name: tmp
          emptyDir: {}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: false
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: secrets
              mountPath: /.kube
            - name: tmp
              mountPath: /tmp
          args:
            - "--port={{ .Values.service.internalPort }}"
            - "--kubeconfig-path=/.kube/config"
            - "--sidebar-resource-types={{ .Values.config.sidebar.resourceTypes }}"
            - "--search-default-resource-types={{ .Values.config.search.defaultResourceTypes }}"
            - "--search-offered-resource-types={{ .Values.config.search.offeredResourceTypes }}"
            - "--search-max-concurrency={{ .Values.config.search.maxConcurrency }}"
            - "--default-label-columns={{ .Values.config.defaultLabelColumns }}"
            - "--object-links={{ .Values.config.objectLinks }}"
            {{- if .Values.config.showContainerLogs }}
            - "--show-container-logs"
            {{- end }}
            {{- if .Values.config.showSecrets }}
            - "--show-secrets"
            {{- end }}
          ports:
            - containerPort:  {{ .Values.service.internalPort }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.internalPort }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.internalPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
