apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "kube-ops-view.fullname" . }}
  labels:
    {{- include "labels.standard" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "labels.standard" . | indent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      volumes:
        - name: secrets
          secret:
            secretName: {{ template "kube-ops-view.fullname" . }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: false
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: secrets
              mountPath: /.kube
          args:
          - --kubeconfig-path=/.kube/config
          {{- if .Values.redis.enabled }}
          - --redis-url=redis://{{ .Release.Name }}-redis-master:{{ .Values.redis.master.port }}
          {{- end }}
          {{- if .Values.linkTemplates.node }}
          - --node-link-url-template={{ .Values.linkTemplates.node }}
          {{- end }}
          {{- if .Values.linkTemplates.pod }}
          - --pod-link-url-template={{ .Values.linkTemplates.pod }}
          {{- end }}
          ports:
          - containerPort: {{ .Values.service.internalPort }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.internalPort }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.internalPort }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 14 }}
