apiVersion: v1
kind: Service
metadata:
  name: {{ template "kube-ops-view.fullname" . }}
  labels:
    {{- include "labels.standard" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: TCP
  selector:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
