apiVersion: v1
name: kube-web-view
version: 0.3.0
appVersion: 21.2.0
description: Kubernetes Web View to list and view all Kubernetes resources
keywords:
- kubernetes
- dashboard
- operations
home: https://kube-web-view.readthedocs.io/
sources:
- https://codeberg.org/hjacobs/kube-web-view
maintainers:
- name: hjacobs
  email: henning@jacobs1.de
