apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "autobahn-worker.fullname" . }}
  labels:
    {{- include "labels.standard" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "labels.standard" . | indent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      hostNetwork: true
      volumes:
        - name: secrets
          secret:
            secretName: {{ .Values.secretRef }}
        - name: scan-data
          emptyDir: {}
        - name: tmp
          emptyDir: {}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: false
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: PYTHONIOENCODING
            value: "utf-8"
          volumeMounts:
            - name: secrets
              mountPath: /usr/src/app/configuration/host/extern
            - name: scan-data
              mountPath: /usr/src/app/scan_data/ 
            - name: tmp
              mountPath: /tmp
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end}}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
