{{- if .Values.airflow.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "airflow-kube-s3.fullname" . }}-env
  labels: {{ include "airflow-kube-s3.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $setting, $option := .Values.airflow.secrets.env }}
  {{ $setting }}: {{ $option | b64enc | quote }}
  {{- end }}
{{- end -}}
