apiVersion: v1
kind: Service
metadata:
  name: {{ template "airflow-kube-s3.fullname" . }}-web
  labels: {{ include "airflow-kube-s3.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
  {{- with .Values.airflow.web.service.annotations }}
  annotations:
    {{- toYaml . | trim | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.airflow.web.service.type }}
  selector: {{ include "airflow-kube-s3.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.airflow.web.port }}
      targetPort: http
